kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    openshift.io/description: "Storage for {{ .Values.app.name }}" 
    openshift.io/display-name: {{ .Values.app.name }}
    argocd.argoproj.io/sync-wave: "-2" 
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem